name: oi-bot-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - requests
  - pandas
  - schedule
  - pandas-ta
  - pyyaml # For parsing config.yaml
  - tenacity # For retry logic
  - loguru # For structured logging
  - pip:
    - openai
